name: tests

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4]

    name: P${{ matrix.php }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-12-php${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo, pdo_sqlite
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction
      - name: Copy Environment File
        run: cp .env.example .env
      - name: Remove Testing Env File
        run: rm .env.testing
      - name: Copy Workflow Testing Env File
        run: cp .env.workflow .env.testing
      - name: Generate App Key
        run: php artisan key:generate
      - name: Install NPM dependencies
        run: npm install
      - name: Build NPM Files
        run: npm run build
      - name: Execute tests
        run: ./vendor/bin/pest
